version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
    command: npm run start:dev

  db:
    image: mariadb:latest
    # container_name: mariadb-dbz
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: oficina-docker
      MARIADB_USER: appuser
      MARIADB_PASSWORD: apppassword
    ports:
      - "3345:3306"
    volumes:
      - oficina-docker:/var/lib/mysql

volumes:
  oficina-docker: