version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: npm run start:dev

    networks:
      - docker-net

  db:
    image: mariadb
    container_name: mariadb-oficina
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '3367:3306'
    volumes:
      - mariadb-oficina-docker:/var/lib/mysql
    networks:
      - docker-net

volumes:
  mariadb-oficina-docker:

networks:
  docker-net:
    driver: bridge